# ?? ?? ??
server:
  port: 8085

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todoapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "0000"
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  profiles:
    include: TodoApp

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true # SQL ?? ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true # SQL pretty print